import '@/app/styles/globals.css';
import Header from '@/app/components/layout/user/header/Header';
import Footer from '@/app/components/layout/user/footer/Footer';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body >
        <div >
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
};
export default RootLayout;
