import '@/app/styles/globals.css';
import Header from '@/app/components/layout/user/header/Header';
import Footer from '@/app/components/layout/user/footer/Footer';
import type { Metadata } from 'next';
import { Alike } from 'next/font/google';

const alike = Alike({
  weight: '400',
  variable: '--font-alike',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en" className={`${alike.variable}`}>
      <body className="bg-coffee-470">
        <div>
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
};
export default RootLayout;
